/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Currency;
import model.CurrencyConversionService;
import model.ExchangeRate;

/**
 * Conversion summary of a bank
 */
public class ConversionSummary extends BasePage {

    /**
     * Creates new form ConversionSummary
     */
    public ConversionSummary(double sourceAmount, Currency sourceCurrency,
            Currency targetCurrency, CurrencyConversionService service) {
        initComponents();
        this.pageTitle.setText("Conversion Summary");
        setData(sourceAmount, sourceCurrency, targetCurrency, service);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exchangeRateLabel = new javax.swing.JLabel();
        feeLabel = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        exchangeRateValue = new javax.swing.JLabel();
        feesValue = new javax.swing.JLabel();
        convertedAmountLabel = new javax.swing.JLabel();
        convertedAmountValue = new javax.swing.JLabel();
        sourceAmountValue = new javax.swing.JLabel();
        sourceAmountLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(super.getTitle());

        exchangeRateLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        exchangeRateLabel.setText("Exchange Rate");

        feeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        feeLabel.setText("Transaction Fee");

        bankLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bankLabel.setText("<Bank Name>");

        exchangeRateValue.setText("<Rate used>");

        feesValue.setText("<Fees Charged>");

        convertedAmountLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        convertedAmountLabel.setText("Net Proceeds");

        convertedAmountValue.setText("<Total Amount>");

        sourceAmountValue.setText("<Source Currency>");

        sourceAmountLable.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        sourceAmountLable.setText("Source Amount");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exchangeRateLabel)
                            .addComponent(feeLabel)
                            .addComponent(convertedAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sourceAmountLable))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(feesValue)
                            .addComponent(exchangeRateValue)
                            .addComponent(convertedAmountValue)
                            .addComponent(sourceAmountValue))))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(bankLabel)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceAmountValue)
                    .addComponent(sourceAmountLable))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exchangeRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exchangeRateValue))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feesValue))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertedAmountLabel)
                    .addComponent(convertedAmountValue))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankLabel;
    private javax.swing.JLabel convertedAmountLabel;
    private javax.swing.JLabel convertedAmountValue;
    private javax.swing.JLabel exchangeRateLabel;
    private javax.swing.JLabel exchangeRateValue;
    private javax.swing.JLabel feeLabel;
    private javax.swing.JLabel feesValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sourceAmountLable;
    private javax.swing.JLabel sourceAmountValue;
    // End of variables declaration//GEN-END:variables

    private void setData(double sourceAmount, Currency sourceCurrency,
            Currency targetCurrency, CurrencyConversionService service) {
        double convertedAmount = service.convertCurrency(sourceAmount, sourceCurrency, targetCurrency);
        ExchangeRate er = service.getCurrentExchangeRate(sourceCurrency, targetCurrency);
        bankLabel.setText(service.getServiceName());
        sourceAmountValue.setText(String.format("%.2f %s", sourceAmount, er.getSource()));
        exchangeRateValue.setText(String.format("1 %s = %.5f %s", er.getSource().name(),
                er.getConversionRate(), er.getTarget().name()));
        feesValue.setText(String.format("%.2f %s", er.getFees(), er.getTarget()));
        convertedAmountValue.setText(String.format("%.2f %s", convertedAmount, er.getTarget()));
    }

}
